version: "2.14.0"

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    network_mode: "host"

  sentiment-analysis:
    image: "wso2/sentiment-api:0.0.1"
    ports:
      - "9098:9098"
    network_mode: "host"
