---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "social_media"
  name: "social-media-sv"
spec:
  ports:
  - name: "port-1-social-m"
    port: 9095
    protocol: "TCP"
    targetPort: 9095
  selector:
    app: "social_media"
  type: "ClusterIP"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: "social_media"
  name: "social-media-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "social_media"
  template:
    metadata:
      labels:
        app: "social_media"
    spec:
      containers:
      - image: "wso2/social-media:0.0.1"
        lifecycle:
          preStop:
            exec:
              command:
              - "sleep"
              - "15"
        name: "social-media-deployment"
        ports:
        - containerPort: 9095
          name: "port-1-social-m"
          protocol: "TCP"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "100Mi"
            cpu: "200m"
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  labels:
    app: "social_media"
  name: "social-media-hp"
spec:
  maxReplicas: 2
  metrics:
  - resource:
      name: "cpu"
      target:
        averageUtilization: 50
        type: "Utilization"
    type: "Resource"
  minReplicas: 1
  scaleTargetRef:
    apiVersion: "apps/v1"
    kind: "Deployment"
    name: "social-media-deployment"
