replicaCount: 1

image:
  repository: wso2/social-media
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 9095

ingress:
  hosts:
    - host: ballerina-socia-media.local
      paths:
        - path: /socialmedia
          pathType: Prefix
  tls: []
